# 公共配置文件

spring:
  profiles:
    # 环境 dev|test|prod
    active: dev
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 320MB
  jackson:
    serialization:
      write-dates-as-timestamps: true

mybatis:
  typeAliasesPackage: com.zty.bo.dao
  mapperLocations: classpath*:mapper/*.xml
  config-location: classpath:mybatis-config.xml

